name: Ansible CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Lint Ansible Playbooks
        run: ansible-lint playbooks/*.yaml

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini playbooks/playbook_web.yaml
